version: '2'
services:
  api:
    env_file:
      - texteditor.desenv.env
    build: .
    image: text-image:v1
    command:  node app.js
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    ports:
      - "3000:3000"